### ISSUE TITLE
Being repeatedly removed and re-invited as a collaborator

### ISSUE THREAD

**Issue by ibrechin** [ministryofjustice/github-collaborators#106] opened 2021-01-28 11:53 UTC
I was added as a collaborator on https://github.com/ministryofjustice/bai2, but after accepting the invite, within 24 hours I was removed as a collaborator and a new invite was sent out. After accepting the invite again, the same thing happened.

**Comment by AntonyBishop** [comment] 2021-02-04 12:18
Hi ibrechin. This would be due to - https://github.com/ministryofjustice/github-collaborators#github-external-collaborators

We need you captured in TF to stop this happening.

You can either raise the change and a PR, or if you don't have access to create a branch then provide me with the following info:

- What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?
- Access level i.e. Read, Triage, Write, Maintain, Admin
- Reason for access
- Which MoJ team/person is responsible for this request? (This should be in the form Awesome Team <awesome.team@digital.justice.gov.uk>)
- Review date for your access (no longer than 1 year from request.

Any problems let me know.

**Comment by ibrechin** [comment] 2021-02-04 15:07
I am captured in TF: https://github.com/ministryofjustice/github-collaborators/blob/953b9144368b5c0097fdef5b7b653b53c1e0b4b1/terraform/bai2.tf

I am assuming that the fact that I am captured in TF is why some automated process keeps on removing me and then re-inviting me.

**Comment by AntonyBishop** [comment] 2021-02-04 16:19
Will investigate.

**Comment by digitalronin** [comment] 2021-02-05 06:40
@ibrechin @AntonyBishop is this still happening?

I'm not sure what's going on here. 

There are 2 ways this repo removes collaborators. 

Collaborators who are defined in terraform, and then get removed (by deleting the terraform code from this repository) are removed by the [Terraform apply](https://github.com/ministryofjustice/github-collaborators/actions?query=workflow%3A%22Terraform+apply%22) github action.

If that happens, we see a line like this in the workflow log:
```
module.mojfile-uploader.github_repository_collaborator.collaborator["jriga"]: Destroying... [id=mojfile-uploader:jriga]
```

The other way is the [Post collaborators JSON](https://github.com/ministryofjustice/github-collaborators/actions?query=workflow%3A%22Post+collaborators+JSON%22) github action, which runs a script that removes all collaborators who *aren't* defined in terraform code.

When that happens every collaborator removed is logged like this:
```
Removing collaborator tomdMOJ from repository security-guidance
```

(There's also a "Remove a collaborator" github action, but that is only ever run manually, supplying the collaborator and repo name when the action is invoked, so it's definitely not involved here)

I've looked through all the workflow logs going back for the last 10 days, and then only relevant mention of `ibrechin` I can see is this:
```
module.bai2.github_repository_collaborator.collaborator["ibrechin"]: Refreshing state... [id=bai2:ibrechin]
```

That's from [this run](https://github.com/ministryofjustice/github-collaborators/runs/1782858709?check_suite_focus=true) 8 days ago, and it implies that, at that point in time, `ibrechin` *was* a collaborator (defined in terraform) on the `bai2` repository.

Whenever the script removes a collaborator, it creates an issue in the relevant repository, like [this one](https://github.com/ministryofjustice/bai2/issues/21). I can only see that one issue, in the bai2 repository.

Because I can't see any mention of removing ibrechin in either set of logs, and because there's only one auto-generated issue on that repo, I don't think it's this project which is removing access to that repository.

I can see a pending invite for ibrechin in that repo:
https://github.com/ministryofjustice/bai2/settings/access

Pending invites are invisible to the code that manages our collaborators, and until you accept the invite, you won't have access.

Please try accepting that invite, and let's see if this happens again. 

If it does, we can try to work through it in realtime when we can run the action and see the results immediately (@AntonyBishop I might have to leave that part to you - all of the relevant actions can be triggered via the Github UI "Run workflow" button, e.g. [here](https://github.com/ministryofjustice/github-collaborators/actions?query=workflow%3A%22Terraform+apply%22), and then just keep an eye on the log output in the github UI.

**Comment by ibrechin** [comment] 2021-02-05 09:29
I stopped accepting the invites because I was getting removed again every time, and unfortunately the last invite I received was on 21st January and when I tried to accept it just now Github said it had expired.

I can give the timestamps for when the invites were sent out (I don't know if this would be the same time that I was removed):
14th Jan - 12:13 (I think this was the initial invite)
14th Jan - 13:36
15th Jan - 05:12
21st Jan - 05:34

**Comment by ibrechin** [comment] 2021-02-05 12:29
I have received new invites which I have now accepted. Let's see if it takes.

**Comment by ibrechin** [comment] 2021-02-09 10:41
As of 10:28 today I appear to have been removed and sent new invites again.

**Comment by AntonyBishop** [comment] 2021-02-09 10:47
Hi @ibrechin thanks for letting us know.

@digitalronin anything that would suggest why this happened?

**Comment by digitalronin** [comment] 2021-02-10 05:48
Hi @ibrechin @AntonyBishop 

The good news is that I can see what happened in the logs. It's the `terraform apply` that removed Ian, after an unrelated change was merged:
```
module.bankline-direct-parser.github_repository_collaborator.collaborator["ibrechin"]: Destroying... [id=bankline-direct-parser:ibrechin]
module.bai2.github_repository_collaborator.collaborator["ibrechin"]: Destroying... [id=bai2:ibrechin]
module.mt940-writer.github_repository_collaborator.collaborator["ibrechin"]: Destroying... [id=mt940-writer:ibrechin]
```

The bad news is that I have no idea why terraform destroyed those collaborations, since they're perfectly well-defined in the code. That's why, a few lines later in the same log we have this:
```
module.bankline-direct-parser.github_repository_collaborator.collaborator["ibrechin"]: Creating...
module.mt940-writer.github_repository_collaborator.collaborator["ibrechin"]: Creating...
module.bai2.github_repository_collaborator.collaborator["ibrechin"]: Creating...
module.bankline-direct-parser.github_repository_collaborator.collaborator["ibrechin"]: Still creating... [10s elapsed]
module.bankline-direct-parser.github_repository_collaborator.collaborator["ibrechin"]: Creation complete after 12s [id=bankline-direct-parser:ibrechin]
module.mt940-writer.github_repository_collaborator.collaborator["ibrechin"]: Still creating... [10s elapsed]
module.mt940-writer.github_repository_collaborator.collaborator["ibrechin"]: Creation complete after 10s [id=mt940-writer:ibrechin]
module.bai2.github_repository_collaborator.collaborator["ibrechin"]: Creation complete after 10s [id=bai2:ibrechin]
```

That's where the new invites come from.

This isn't happening to anyone else, so my current thinking is that perhaps the terraform state has become corrupted in some strange way. So, I'm going to try the following:

1. Manually remove the current batch of pending invites for ibrechin to those 3 repos
2. Remove the terraform definitions of those 3 collaborations, merge and terraform apply
3. Replace the terraform definitons, merge and terraform apply again

I'm hoping that will reset the terraform state wrt. those collaborations.

At the end of this process, there will be 3 pending invitations. **@ibrechin please accept those ASAP** - it's possible this has something to do with pending invites persisting through multiple terraform applies. 

Since pending invites are invisible via the github API, I can imagine things might get confusing (e.g. because the invite hasn't been accepted, another collaboration is created, but then the first one gets accepted and terraform is confused from that point onwards - just a theory).

**Comment by digitalronin** [comment] 2021-02-10 08:16
@AntonyBishop You were absolutely right - the problem is the "maintain" permission. 

"maintain" and "triage" won't work, because the github API only (and incorrectly) returns "pull", "push" or "admin" once you create the collaboration (see [this issue comment](https://github.com/integrations/terraform-provider-github/issues/480#issuecomment-636590471)). So, terraform always things the permission is incorrect, and recreates the collaboration on every `terraform apply`.

I can reproduce this problem if I set permission to "maintain" or "triage" - as soon as I accept the invitation, terraform recreates the collaboration on the next run. The two people affected by this issue are the only collaborators who were given "maintain" permissions on the relevant repositories.

Changing to "push" makes everything work fine, and it doesn't make any difference when you accept the invitation.

I've changed the affected collaborations to "push" via #117 so as soon as the users accept the latest invitations, everything should be fine.

**Closed** 2021-02-10 08:19 UTC
